services:
  db:
    image: mysql:8.0
    container_name: olist_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pro_password_2024
      MYSQL_DATABASE: olist_db
    ports:
      - "3306:3306"